### PR TITLE
added saveOnBlur support for custom editComponent by passing the onBlur function as prop

### PR DESCRIPTION
**Pull request by mrrenaud**
This PR is related to #116.

Let me know if you have any remarks about it :)

### CODE REVIEW

**Comment by mrrenaud** [comment]
I noticed that the current rollup config isn't building. It looks like the config (uglify) doesn't support arrow functions.

image

I tried some changes but it looks like the smallest change that I can propose to fix it is to use terser (https://github.com/TrySound/rollup-plugin-terser) instead of uglify, as recommended in a note on the readme (https://github.com/TrySound/rollup-plugin-uglify).

Should I also commit this change?

**Comment by giorgosart** [comment]
Hey @mrrenaud thank you for submitting this PR for review. I know the builds are failing because of that, they didn't used to but now they do. I am about to commit a few changes to the `package.json` and `rollup.config.js` that will include the change you've proposed so please hold back on committing your changes around terser. I will review this PR as soon as I can.

**Comment by giorgosart** [comment]
@mrrenaud can you please `master` in this PR and let me know if you are still facing build issues?

**Comment by mrrenaud** [comment]
Thanks @giorgosart, this is building fine now!

**Comment by mrrenaud** [comment]
Hi @giorgosart, no pressure but do you think this could be merged anytime soon? I'm interested in using this fix in a project I'm working on. I could use the sources directly but prefer to stick with the npm package if possible 😄 

Let me know what's your agenda and if you need me to do anything else to get this accepted.

**Review by giorgosart — APPROVED** [review]

**Pull request merged**
