### PR TITLE
feat(docs): update installation readme documentation

### PR DESCRIPTION
**Pull request by ferrorenan**
Hey @giorgosart 

I made a small update to the readme in the Installation stage.

Could you take a look and schedule Hacktoberfest, please?!

### CODE REVIEW

**Review by giorgosart — CHANGES_REQUESTED** [review]
@ferrorenan can you please pull the latest master in your branch?

**Comment by ferrorenan** [comment]
@giorgosart I did it, Is it correct now?!

**Comment by giorgosart** [comment]
@ferrorenan closing down this PR as there is nothing in it, you are just splitting a line into two different ones. Feel free to pick up a ticket from the issues tab if you want to contribute to this library.

**Comment by ferrorenan** [comment]
Hey @giorgosart , how are you?!

OK no problem!

I separated the installations because normally in repositories we see the installations separately, which in my opinion makes sense because it is easier to view and more isolated!

But no problem, thanks for the feedback and I'll take a look at the issues!

**Pull request closed without merging**
